# -*- coding: utf-8 -*-
{
    'name': 'Stock Extended',
    'category': 'Stock',
    'summary': 'Add new features to stock module',
    'depends': ['base', 'stock', 'purchase', 'sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/stock_move_line.xml',
        'views/stock_picking_views.xml',
        'views/product_template_views.xml',
        'views/product_product.xml',
        'views/report_package_barcode.xml',
        'views/stock_quant.xml',
        'views/stock_quant_package.xml',
        'views/stock_packages_desglose_views.xml',
        'views/stock_repacking_views.xml',
        'views/color_family_views.xml',
        'views/product_attribute_value_views.xml',
        'views/tipo_cono_views.xml',
        'views/menu_items.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'data/cron_job.xml',
        'views/stock_quant_package_zpl_label.xml'
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
